apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-3"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}-config-prepare"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: qbt-config-injector
          image: python:3.11-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: TORRENT_USERNAME
              value: {{ .Values.torrent.username }}
            - name: TORRENT_PASSWORD
              value: {{ .Values.torrent.password }}
          command:
            - "/bin/sh"
            - "-ec"
          args:
            - "python3 -m pip install --no-cache-dir Jinja2 >/dev/null 2>&1 && python3 -u /tmp/init-qbittorrent.py 2>&1;"
          volumeMounts:
            - name: torrent-config-volume
              mountPath: /config
            - name: init-script
              mountPath: /tmp/init-qbittorrent.py
              subPath: init-qbittorrent.py 
      volumes:
      - name: torrent-config-volume
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.torrentConfig.name }}
      - name: init-script
        configMap:
          name: init-qbittorrent-python-script
          defaultMode: 0644
