name: Helm Chart Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to release from
        type: string
        required: true
        default: dev

permissions:
  contents: read # checkout
  packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CHART_DIR: servarr
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: Set up crane
        uses: imjasonh/setup-crane@v0.4

      - name: Fetch cached dependencies charts
        id: cache-charts
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CHART_DIR }}/charts
          key: dep-charts-${{ hashFiles('servarr/Chart.yaml') }}

      - name: Helm Dependency update
        if: ${{ steps.cache-charts.outputs.cache-hit != 'true' }}
        run: helm dependency update ${{ env.CHART_DIR }}/ --debug

      - name: Save dependencies charts in the cache
        if: ${{ steps.cache-charts.outputs.cache-hit != 'true' }}
        id: cache-charts-save
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CHART_DIR }}/charts
          key: dep-charts-${{ hashFiles('servarr/Chart.yaml') }}

      - name: Prepare package directory
        run: mkdir -p dist

      - name: Create Package
        run: helm package ${{ env.CHART_DIR }}/ --destination dist

      - name: Get chart version
        id: chart-version
        run: |
          version=$(grep '^version:' "${CHART_DIR}/Chart.yaml" | awk '{print $2}')
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Authenticate to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | helm registry login ghcr.io --username "${{ github.actor }}" --password-stdin
          crane auth login ghcr.io -u "${{ github.actor }}" -p "${GITHUB_TOKEN}"

      - name: Remove existing package version (if present)
        env:
          VERSION: ${{ steps.chart-version.outputs.version }}
        run: |
          crane delete "${REGISTRY}/servarr:${VERSION}" || echo "No existing package version to remove"

      - name: Push chart to GHCR
        env:
          VERSION: ${{ steps.chart-version.outputs.version }}
        run: helm push "dist/servarr-${VERSION}.tgz" "oci://${REGISTRY}"
